export const languageTxt: any = {
  // ErrorMessages
  txtUserNameError: 'Username is required',
  txtPasswordError: 'Password is required',
  txtAccRegCodeError: 'Account No./ Registration No is required',
  txtCompanyNameError: 'Company Name is required',
  txtNTNError: 'National Tax Number (NTN) is required',
  txtCompIncorporationNumberError: 'Company Registration Number is required',
  txtAuthPersonNameError: 'Authorized Person Name is required',
  txtAuthPersonCNICError: 'Authorized Person CNIC is required',
  txtEmailError: 'Email ID (only company domain email id required) is required',
  txtRegContactError: 'Registered Contact is required',
  txtRegAddressError: 'Registered Address is required',
  txtNameError: 'Applicant Name is required',
  txtRegEmailError: 'Registered E-mail address is required',
  txtRegMobileNumError: 'Mobile Number is required',
  txtRegNoError: 'Folio Number is required',
  txtCNICError: 'CNIC(XXXXXXXXXXXXX) is required',
  txtDOBError: 'Date of Birth(DD/MM/YYYY) is required',
  txtCNICIssueDateError: 'CNIC Issue date(DD/MM/YYYY) is required',
  txtCNICExpiryDateError: 'CNIC Expiry date(DD/MM/YYYY) is required',
  txtSpouseError: 'Father/Spouse Name is required',
  txtAddressError: 'Address is required',
  txtNationalityError: 'Nationality is required',
  txtBankAccountNumError: 'Bank Acc. Number is required',
  txtIBAN_NumberError: 'IBAN Number is required',
  txtKnowError: 'Know is required',
  ddlGenderError: 'Gender is required',
  ddlCityError: 'City is required',
  ddlCountryError: 'Country is required',
  ddlOccupationError: 'Occupation is required',
  ddlSourceOfIncomeError: 'Income Source is required',
  ddlBankError: 'Bank is required',
  ddlAdvisorError: 'Advisor is required',

  emailPatternError: 'Invalid email address',
  invalidUsernameOrPassword: 'Invalid credentials!',
  unexpectedError: 'Something went wrong!',
  tryAgainLater: 'Could not post at this time. Try again later.',

  // InputPlaceholder
  txtUserName: 'Username',
  txtPassword: 'Password',
  txtAccRegCode: 'Account No./ Registration No',
  txtCompanyName: 'Company Name',
  txtNTN: 'National Tax Number (NTN)',
  txtCompIncorporationNumber: 'Company Registration Number',
  txtAuthPersonName: 'Authorized Person Name',
  txtAuthPersonCNIC: 'Authorized Person CNIC',
  txtEmail: 'Email ID (only company domain email id required)',
  txtRegContact: 'Registered Contact',
  txtRegAddress: 'Registered Address',
  txtName: 'Applicant Name',
  txtRegEmail: 'Registered E-mail address',
  txtRegMobileNum: 'Mobile Number',
  txtRegNo: 'Folio Number',
  txtCNIC: 'CNIC(XXXXXXXXXXXXX)',
  txtDOB: 'Date of Birth(DD/MM/YYYY)',
  txtCNICIssueDate: 'CNIC Issue date(DD/MM/YYYY)',
  txtCNICExpiryDate: 'CNIC Expiry date(DD/MM/YYYY)',
  txtSpouse: 'Father/Spouse Name',
  txtAddress: 'Address',
  txtNationality: 'Nationality',
  txtBankAccountNum: 'Bank Acc. Number',
  txtIBAN_Number: 'IBAN Number',
  txtKnow: 'How Did You Know About Pak Oman?',
  // Select
  ddlGender: 'Select Gender',
  ddlCity: 'Select City',
  ddlCountry: 'Select Country',
  ddlOccupation: 'Select Occupation',
  ddlSourceOfIncome: 'Select Income Source',
  ddlBank: 'Select Bank',
  ddlAdvisor: 'Select Advisor',
  FileUpload1: '',

  login: 'Login',
  openAccount: 'Open an Account',
  forgotUsername: 'Forgot Username?',
  submitRequest: 'Submit Request',
  clear: 'Clear',
  register: 'Register',

  selectYourInvestmentTypeCap: 'SELECT YOUR INVESTMENT TYPE',
  servicesRequestFormForCorporateInvestorsCap:
    'SERVICES REQUEST FORM FOR CORPORATE INVESTORS',
  onlineServicesRequestCap: 'ONLINE SERVICES REQUEST',
  sahulatSarmayakariAccountCap: 'SAHULAT SARMAYAKARI ACCOUNT',

  onlineServicesRequest: 'Online Services Request',
  investorWelcome:
    'Welcome to Online Service Registration for PakOman Investments.',
  investorWelcome2:
    'Please kindly fill out the fields as below and submit. A customer service representative will be in touch shortly. Please note mandatory fields are marked with an *',
  investorWelcome3:
    'If you need assistance please email us on xxx@XXXXX.com or call 021-xxx-Xxx-xxx',
  sahulatSarmayakariAccountInfo:
    'Please enter your infomation and proceed to the next step so we can build your accounts.',
  sahulatSarmayakariAccountOpen:
    'Not yet PakomanInvestor? Open a New Sahulat Sarmayakari Account',
  copyrights: '© All Copyrights Reserved - Powered By Sidat Hyder',

  //Stacks and Screen
  reactStackKeys: {
    auth: {
      login: 'Login',
      register: {
        name: 'Register',
        investorTypes: 'Investor Types',
        corporateInvestor: 'Corporate Investor',
        individualInvestor: 'Individual Investor',
        pensionInvestor: 'Pension Investor',
        sahulatSarmayakari: 'Sahulat Sarmayakari',
      },
    },
  },
};
